### ISSUE TITLE
PROD ERROR: Client disconnects from database causing 500 error until restart

### ISSUE THREAD

**Issue by darrengeary** [basir/next-tailwind-amazona#9]
This happens on a fresh git clone. In development environment it works fine but when in production it will disconnect when you try to login. 

I set NODE_ENV="production" in ENV variables to allow disconnect function but it makes no difference. It seems to get disconnected outside of the disconnect function. 

New Connection
Already Connected
MongoNotConnectedError: Client must be connected before running operations
    at executeOperationAsync (/var/www/irishimpressions/node_modules/mongodb/lib/operations/execute_operation.js:24:19)
    at /var/www/irishimpressions/node_modules/mongodb/lib/operations/execute_operation.js:12:45
    at maybeCallback (/var/www/irishimpressions/node_modules/mongodb/lib/utils.js:338:21)
    at executeOperation (/var/www/irishimpressions/node_modules/mongodb/lib/operations/execute_operation.js:12:38)
    at FindCursor._initialize (/var/www/irishimpressions/node_modules/mongodb/lib/cursor/find_cursor.js:54:50)
    at FindCursor.[kInit] (/var/www/irishimpressions/node_modules/mongodb/lib/cursor/abstract_cursor.js:444:14)
    at next (/var/www/irishimpressions/node_modules/mongodb/lib/cursor/abstract_cursor.js:512:22)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at next (node:internal/util:346:12) {
  [Symbol(errorLabels)]: Set(0) {}
}

**Comment by MuhammadZunnoorainRafi** [comment]
will you get a solution for this problem?

**Comment by tapamind** [comment]
I have the same problem, did you solve it?
